web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./:/symfony
    - ./symfony.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: php:7-fpm
  volumes:
    - ./:/symfony
  links:
    - mysql
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: symfony
    MYSQL_USER: symfony
    MYSQL_PASSWORD: symfony
